name: CD

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.19
      with:
        name: bots/madness
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.defman.me
        cache: ${{ github.event_name != 'schedule' }}
        tags: "latest"
